version: "3"
services:
    www:
        build: .
        container_name: arlit
        ports:
            - "82:80"
        volumes:
            - .:/var/www/html/
        networks:
            - default